name: Run CI tests

on: [push]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Prepare java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: 1.11.1.1113

      - name: Run CI tests
        # run: clojure -M:test
        run: clojure -T:build ci
